# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='product.ProductFeature', to='product.Feature'),
        ),
    ]
