# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='value',
            field=models.CharField(default='not_set', max_length=200, verbose_name='value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='created at'),
        ),
    ]
