# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20190808_2301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('wait', 'wait'), ('cancel', 'cancel'), ('success', 'success')], max_length=20)),
            ],
            options={
                'ordering': ['created_at', 'user'],
            },
        ),
        migrations.CreateModel(
            name='OrderProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('number', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductFeature')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_features',
            field=models.ManyToManyField(through='order.OrderProductFeature', to='product.ProductFeature'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
